// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Nw7ewfKlmjPu34KB3JqoQcJ9OxIKQOA',
    appId: '1:837828423082:web:e06c8ea2717dbe7d170fd3',
    messagingSenderId: '837828423082',
    projectId: 'test-crud-81425',
    authDomain: 'test-crud-81425.firebaseapp.com',
    storageBucket: 'test-crud-81425.appspot.com',
    measurementId: 'G-2LH21YV2EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-f97g-0KPl-UZoAvLEx0CoTaUPQSmS1Y',
    appId: '1:837828423082:android:d4318c0e2d8f8a09170fd3',
    messagingSenderId: '837828423082',
    projectId: 'test-crud-81425',
    storageBucket: 'test-crud-81425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfAlbF8rS5S6syCukdUWYAjjr4K8zD13c',
    appId: '1:837828423082:ios:acde61faf3852161170fd3',
    messagingSenderId: '837828423082',
    projectId: 'test-crud-81425',
    storageBucket: 'test-crud-81425.appspot.com',
    iosBundleId: 'com.example.testcrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfAlbF8rS5S6syCukdUWYAjjr4K8zD13c',
    appId: '1:837828423082:ios:d5eff3349d580afe170fd3',
    messagingSenderId: '837828423082',
    projectId: 'test-crud-81425',
    storageBucket: 'test-crud-81425.appspot.com',
    iosBundleId: 'com.example.testcrud.RunnerTests',
  );
}
